version: "3.3"
services:
  nginx:
    build: ./docker/nginx/
    container_name: todoapp-nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:
      - .:/var/www/todoapp/

  php:
    build:
      context: ./docker/php/
      args:
        - host_ip="172.17.0.1"
    container_name: todoapp-php-container
    expose:
      - 9000
    volumes:
      - .:/var/www/todoapp/