#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_index:
    path: /
    controller: App\Controller\DefaultController::index

tasks:
    type:     rest
    host:     localhost
    resource: App\Controller\TasksController